/**
 * IPL 2026 player seed data for bulk insert into ipl_players.
 * Fields: name, team, role, isActive, isEmerging.
 */
export type IPLPlayerSeed = {
  name: string;
  team: string;
  role: 'batsman' | 'bowler' | 'allrounder';
  isActive: boolean;
  isEmerging: boolean;
};

export const IPL_2026_PLAYERS_SEED: IPLPlayerSeed[] = [
  { name: 'Rohit Sharma', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Ishan Kishan', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Suryakumar Yadav', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Tilak Varma', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Hardik Pandya', team: 'Mumbai Indians', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Tim David', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Romario Shepherd', team: 'Mumbai Indians', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Nehal Wadhera', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Dewald Brevis', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Jasprit Bumrah', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Gerald Coetzee', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Akash Madhwal', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Piyush Chawla', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Shams Mulani', team: 'Mumbai Indians', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Arjun Tendulkar', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'MS Dhoni', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Ruturaj Gaikwad', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Devon Conway', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Ajinkya Rahane', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Sameer Rizvi', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Shivam Dube', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Ravindra Jadeja', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Moeen Ali', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Mitchell Santner', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Deepak Chahar', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Tushar Deshpande', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Matheesha Pathirana', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Virat Kohli', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Faf du Plessis', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Rajat Patidar', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Anuj Rawat', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Glenn Maxwell', team: 'Royal Challengers Bangalore', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Cameron Green', team: 'Royal Challengers Bangalore', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Mahipal Lomror', team: 'Royal Challengers Bangalore', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Dinesh Karthik', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Mohammed Siraj', team: 'Royal Challengers Bangalore', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Yash Dayal', team: 'Royal Challengers Bangalore', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Shreyas Iyer', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Rinku Singh', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Nitish Rana', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Venkatesh Iyer', team: 'Kolkata Knight Riders', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Andre Russell', team: 'Kolkata Knight Riders', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Sunil Narine', team: 'Kolkata Knight Riders', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Rahmanullah Gurbaz', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Mitchell Starc', team: 'Kolkata Knight Riders', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Varun Chakravarthy', team: 'Kolkata Knight Riders', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Aiden Markram', team: 'Sunrisers Hyderabad', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Heinrich Klaasen', team: 'Sunrisers Hyderabad', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Rahul Tripathi', team: 'Sunrisers Hyderabad', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Abhishek Sharma', team: 'Sunrisers Hyderabad', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Washington Sundar', team: 'Sunrisers Hyderabad', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Bhuvneshwar Kumar', team: 'Sunrisers Hyderabad', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Umran Malik', team: 'Sunrisers Hyderabad', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Pat Cummins', team: 'Sunrisers Hyderabad', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Sanju Samson', team: 'Rajasthan Royals', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Jos Buttler', team: 'Rajasthan Royals', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Yashasvi Jaiswal', team: 'Rajasthan Royals', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Riyan Parag', team: 'Rajasthan Royals', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Ravichandran Ashwin', team: 'Rajasthan Royals', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Trent Boult', team: 'Rajasthan Royals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Yuzvendra Chahal', team: 'Rajasthan Royals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Rishabh Pant', team: 'Delhi Capitals', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'David Warner', team: 'Delhi Capitals', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Prithvi Shaw', team: 'Delhi Capitals', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Axar Patel', team: 'Delhi Capitals', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Mitchell Marsh', team: 'Delhi Capitals', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Kuldeep Yadav', team: 'Delhi Capitals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Anrich Nortje', team: 'Delhi Capitals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Shikhar Dhawan', team: 'Punjab Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Jonny Bairstow', team: 'Punjab Kings', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Liam Livingstone', team: 'Punjab Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Sam Curran', team: 'Punjab Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Arshdeep Singh', team: 'Punjab Kings', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Kagiso Rabada', team: 'Punjab Kings', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'KL Rahul', team: 'Lucknow Super Giants', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Quinton de Kock', team: 'Lucknow Super Giants', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Nicholas Pooran', team: 'Lucknow Super Giants', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Marcus Stoinis', team: 'Lucknow Super Giants', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Krunal Pandya', team: 'Lucknow Super Giants', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Ravi Bishnoi', team: 'Lucknow Super Giants', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Mark Wood', team: 'Lucknow Super Giants', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Shubman Gill', team: 'Gujarat Titans', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Sai Sudharsan', team: 'Gujarat Titans', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'David Miller', team: 'Gujarat Titans', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Rahul Tewatia', team: 'Gujarat Titans', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Rashid Khan', team: 'Gujarat Titans', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Mohammed Shami', team: 'Gujarat Titans', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Noor Ahmad', team: 'Gujarat Titans', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Kumar Kartikeya', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Hrithik Shokeen', team: 'Mumbai Indians', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Vishnu Vinod', team: 'Mumbai Indians', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Rajvardhan Hangargekar', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Nishant Sindhu', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Mukesh Choudhary', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Suyash Prabhudessai', team: 'Royal Challengers Bangalore', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Vyshak Vijaykumar', team: 'Royal Challengers Bangalore', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Manoj Bhandage', team: 'Royal Challengers Bangalore', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Suyash Sharma', team: 'Kolkata Knight Riders', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Angkrish Raghuvanshi', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Mayank Agarwal', team: 'Sunrisers Hyderabad', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Marco Jansen', team: 'Sunrisers Hyderabad', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Dhruv Jurel', team: 'Rajasthan Royals', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Navdeep Saini', team: 'Rajasthan Royals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Yash Dhull', team: 'Delhi Capitals', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Lalit Yadav', team: 'Delhi Capitals', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Jitesh Sharma', team: 'Punjab Kings', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Rahul Chahar', team: 'Punjab Kings', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Ayush Badoni', team: 'Lucknow Super Giants', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Yudhvir Singh', team: 'Lucknow Super Giants', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Wriddhiman Saha', team: 'Gujarat Titans', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Vijay Shankar', team: 'Gujarat Titans', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Anshul Kamboj', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Mohd Arshad Khan', team: 'Mumbai Indians', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Nuwan Thushara', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Luke Wood', team: 'Mumbai Indians', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Shaik Rasheed', team: 'Chennai Super Kings', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Prashant Solanki', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Ajay Mandal', team: 'Chennai Super Kings', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Lockie Ferguson', team: 'Royal Challengers Bangalore', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Tom Curran', team: 'Royal Challengers Bangalore', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Sherfane Rutherford', team: 'Kolkata Knight Riders', role: 'batsman', isActive: true, isEmerging: false },
  { name: 'Mujeeb Ur Rahman', team: 'Kolkata Knight Riders', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Glenn Phillips', team: 'Sunrisers Hyderabad', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Fazalhaq Farooqi', team: 'Sunrisers Hyderabad', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Kuldeep Sen', team: 'Rajasthan Royals', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Donovan Ferreira', team: 'Rajasthan Royals', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Ishant Sharma', team: 'Delhi Capitals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Khaleel Ahmed', team: 'Delhi Capitals', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Harpreet Brar', team: 'Punjab Kings', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Nathan Ellis', team: 'Punjab Kings', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Deepak Hooda', team: 'Lucknow Super Giants', role: 'allrounder', isActive: true, isEmerging: false },
  { name: 'Mohsin Khan', team: 'Lucknow Super Giants', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Joshua Little', team: 'Gujarat Titans', role: 'bowler', isActive: true, isEmerging: false },
  { name: 'Abhinav Manohar', team: 'Gujarat Titans', role: 'batsman', isActive: true, isEmerging: true },
  { name: 'Kartik Tyagi', team: 'Sunrisers Hyderabad', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'R Sai Kishore', team: 'Gujarat Titans', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Abdul Samad', team: 'Sunrisers Hyderabad', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Akash Singh', team: 'Chennai Super Kings', role: 'bowler', isActive: true, isEmerging: true },
  { name: 'Prerak Mankad', team: 'Lucknow Super Giants', role: 'allrounder', isActive: true, isEmerging: true },
  { name: 'Kuldip Yadav (wk)', team: 'Rajasthan Royals', role: 'batsman', isActive: true, isEmerging: true },
];
